# Generated by Django 5.2.1 on 2025-05-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_alter_lockcommand_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('product_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('original_transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('purchase_date', models.DateTimeField()),
                ('client_reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
    ]
