# Generated by Django 4.2.21 on 2025-05-10 03:20

from django.db import migrations, models
import message_agent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PGPMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='PGP加密信息')),
                ('short_id', models.CharField(default=message_agent.models.generate_short_id, max_length=10, unique=True, verbose_name='短链接ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expiry_minutes', models.IntegerField(choices=[(10, '10分钟'), (60, '1小时'), (1440, '1天')], default=60, verbose_name='过期时间')),
                ('one_time_view', models.BooleanField(default=False, verbose_name='一次性查看')),
                ('has_been_viewed', models.BooleanField(default=False, verbose_name='已被查看')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='访问密码')),
            ],
        ),
    ]
