# Generated by Django 3.2.25 on 2025-05-15 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgpmessage',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='PGP加密信息'),
        ),
        migrations.AlterField(
            model_name='pgpmessage',
            name='expiry_minutes',
            field=models.IntegerField(choices=[(10, '10分钟'), (30, '30分钟'), (60, '1小时'), (240, '4小时')], default=60, verbose_name='过期时间'),
        ),
    ]
