server {
    listen 80;
    server_name si4key.com www.si4key.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name si4key.com www.si4key.com;

    ssl_certificate /etc/letsencrypt/live/si4key.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/si4key.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /relay/static/ {
        alias /root/message_relay_api/staticfiles/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location /relay/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/root/message_relay_api/message_relay.sock;
    }

    error_page 404 /404.html;
    location = /40x.html {}

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {}
}
